import "./globals.css";
import React, { PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { type Metadata } from "next";
import { cn } from "@/lib/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const GlobalLayout = ({ children }: PropsWithChildren) => {
	return (
		<html lang="en">
			<body className={cn(inter.className, "overscroll-none")}>{children}</body>
		</html>
	);
};

export default GlobalLayout;
